/* Generated by Together */

package io.github.icodegarden.nutrient.designpattern.composite_safe;

public class Leaf implements Component {
    public Composite getComposite(){
        // Write your code here
        return null;
    }

    public void sampleOperation(){
        // Write your code here
    }
}
